apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: back
spec:
  replicas: 1
  selector:
    matchLabels:
      name: api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: api
    spec:
      containers:
        - env:
            - name: "POSTGRES_DB"
              value: "persons"
            - name: "POSTGRES_USER"
              value: "user"
            - name: "POSTGRES_PASSWORD"
              value: "password"
            - name: "POSTGRES_HOST"
              value: "10.43.0.5"
          image: ghcr.io/do3-2023/vfo-kube/back:latest
          imagePullPolicy: Always
          name: api
      imagePullSecrets:
        - name: ghcr-secret