apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: back
spec:
  selector:
    name: api
  clusterIP: 10.43.0.6
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP