apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: back
spec:
  selector:
    name: api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31338
  type: NodePort