apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: db
spec:
  selector:
    name: vfodb
  clusterIP: 10.43.0.5
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP