apiVersion: v1
kind: Service
metadata:
  name: front-service
  namespace: front
spec:
  selector:
    name: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4173
      nodePort: 31337
  type: NodePort